name: Deploy Laravel (ZIP Fast Deploy)

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          tools: composer

      - name: Check if composer files changed
        id: composer_changed
        run: |
          echo "Files changed:"
          echo "${{ toJson(github.event.head_commit.modified) }}"
          if echo "${{ toJson(github.event.head_commit.modified) }}" | grep -q "composer.json"; then
            echo "changed=true" >> $GITHUB_OUTPUT
          elif echo "${{ toJson(github.event.head_commit.modified) }}" | grep -q "composer.lock"; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Install composer (ONLY WHEN NEEDED)
        if: steps.composer_changed.outputs.changed == 'true'
        run: composer install --no-dev --optimize-autoloader

      - name: Check if npm files changed
        id: npm_changed
        run: |
          echo "changed=false" >> $GITHUB_OUTPUT
          if echo "${{ toJson(github.event.head_commit.modified) }}" | grep -q "package.json"; then
            echo "changed=true" >> $GITHUB_OUTPUT
          elif echo "${{ toJson(github.event.head_commit.modified) }}" | grep -q "package-lock.json"; then
            echo "changed=true" >> $GITHUB_OUTPUT
          elif echo "${{ toJson(github.event.head_commit.modified) }}" | grep -q "vite.config.js"; then
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Install Node & Build (ONLY IF NEEDED)
        if: steps.npm_changed.outputs.changed == 'true'
        run: |
          npm install
          npm run build

      - name: Create deployment ZIP
        run: zip -r deploy.zip . -x ".git/*" "node_modules/*" ".github/*" ".env"

      - name: Upload ZIP to Hostinger
        uses: SamKirkland/FTP-Deploy-Action@v4.3.0
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          port: 21
          local-dir: "./"
          server-dir: "/test-action/"
          exclude: |
            **
            !deploy.zip
      - name: Call unzip script on Hostinger
        run: curl https://test-action.a2ztechlabs.in/unzip.php

